DROP DATABASE IF EXISTS Megafarma;
CREATE DATABASE IF NOT EXISTS Megafarma; 
USE Megafarma; 
CREATE TABLE Clientes (
   NomeCliente VARCHAR(30) NOT NULL,
   CPFCliente VARCHAR(14) NOT NULL,
   CorFavorita VARCHAR(20) NOT NULL
);
CREATE TABLE Pedidos (
IDVenda INT NOT NULL PRIMARY KEY,
DataDoBagulho DATETIME NOT NULL,
IDCliente INT NOT NULL
);
ALTER TABLE Clientes
ADD COLUMN IDCliente INT NOT NULL FIRST;
ALTER TABLE Clientes
ADD COLUMN Endereco VARCHAR(10) NULL AFTER CPFCliente;
ALTER TABLE Clientes
MODIFY COLUMN Endereco VARCHAR(50) NOT NULL;
ALTER TABLE Clientes
MODIFY COLUMN CorFavorita TINYINT NOT NULL;
ALTER TABLE Pedidos
CHANGE COLUMN DataDoBagulho DataVenda DATETIME NOT NULL;
ALTER TABLE Pedidos
RENAME TO Vendas;
ALTER TABLE Clientes
DROP COLUMN CorFavorita;
ALTER TABLE Clientes
ADD CONSTRAINT PK_Clientes PRIMARY KEY (IDCliente);
ALTER TABLE Vendas
ADD CONSTRAINT FK_Vendas_Clientes FOREIGN KEY (IDCliente)
REFERENCES Clientes(IDCliente);
ALTER TABLE Clientes
ADD COLUMN Bairro VARCHAR(30) NOT NULL,
ADD COLUMN CEP VARCHAR(8),
MODIFY COLUMN NomeCliente VARCHAR(50) NOT NULL,
CHANGE COLUMN Endereco Logradouro VARCHAR(100) NOT NULL;

/* mysql -h localhost -u root -p < script (no caso seria aaa.sql) */