/** 
 * Henzo Possebon Ayres RM22706 & Henrique Silva Barbosa RM22687
 * */
DROP DATABASE IF EXISTS Locadora;
CREATE DATABASE IF NOT EXISTS Locadora;
USE Locadora;

CREATE TABLE Clientes(
	NomeCliente VARCHAR(25) NOT NULL,
	CPF VARCHAR(15) NOT NULL,
	Telefone VARCHAR(14) NOT NULL
);
ALTER TABLE Clientes
	ADD COLUMN IDCliente INT NOT NULL PRIMARY KEY FIRST,
	ADD COLUMN Endereco VARCHAR(50) NOT NULL AFTER NomeCliente;

CREATE TABLE Alugueis(
	Data date NOT NULL,
	IDCliente INT NOT NULL,
	CONSTRAINT FK_Alugueis_Clientes FOREIGN KEY (IDCliente) 
		REFERENCES Clientes(IDCliente)
);
ALTER TABLE Alugueis
	ADD COLUMN Comprovante INT NOT NULL PRIMARY KEY FIRST,
	ADD COLUMN Devolucao date NOT NULL AFTER Data;	
CREATE TABLE Filmes(
	IDFilme INT NOT NULL PRIMARY KEY,
	Idade VARCHAR(3)
);
ALTER TABLE Filmes
	ADD COLUMN Titulo VARCHAR(30) NOT NULL,
	ADD COLUMN Genero VARCHAR(25) NOT NULL,
	ADD COLUMN Idioma VARCHAR(20) NOT NULL,
	ADD COLUMN Preco DECIMAL(5.2) NOT NULL,
	DROP COLUMN Idade;
CREATE TABLE ItensAlugados(
	Comprovante INT NOT NULL PRIMARY KEY,
	IDCliente INT NOT NULL,
	CONSTRAINT FK_ItensAlugados_Clientes FOREIGN KEY(IDCliente)
		REFERENCES Clientes(IDCliente)
		);
ALTER TABLE ItensAlugados
	ADD COLUMN QtdeEstoque INT NOT NULL;