/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.Random;

/**
 *
 * @author LAB03M05
 */
public class Jokenpo_GUI extends javax.swing.JFrame {
    int contplayer=0, contbot=0;
    String player = "0", bot="0";

    public Jokenpo_GUI() {
        initComponents();
        PapelBot.setVisible(false);
        PedraBot.setVisible(false);
        TesouraBot.setVisible(false);
        tryagain.setVisible(false);
        PontBot.setText(bot);
        PontPlayer.setText(player);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tesoura = new org.edisoncor.gui.panel.PanelImage();
        papel = new org.edisoncor.gui.panel.PanelImage();
        pedra = new org.edisoncor.gui.panel.PanelImage();
        PedraBot = new org.edisoncor.gui.panel.PanelImage();
        PapelBot = new org.edisoncor.gui.panel.PanelImage();
        TesouraBot = new org.edisoncor.gui.panel.PanelImage();
        TesouraButton = new javax.swing.JButton();
        PapelButton = new javax.swing.JButton();
        PedraButton = new javax.swing.JButton();
        PontPlayer = new javax.swing.JLabel();
        PontBot = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        tryagain = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(300, 400));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        tesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/tesoura.png"))); // NOI18N

        javax.swing.GroupLayout tesouraLayout = new javax.swing.GroupLayout(tesoura);
        tesoura.setLayout(tesouraLayout);
        tesouraLayout.setHorizontalGroup(
            tesouraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tesouraLayout.setVerticalGroup(
            tesouraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(tesoura);
        tesoura.setBounds(40, 30, 100, 100);

        papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/papel.png"))); // NOI18N

        javax.swing.GroupLayout papelLayout = new javax.swing.GroupLayout(papel);
        papel.setLayout(papelLayout);
        papelLayout.setHorizontalGroup(
            papelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        papelLayout.setVerticalGroup(
            papelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(papel);
        papel.setBounds(220, 30, 100, 100);

        pedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pedra.png"))); // NOI18N

        javax.swing.GroupLayout pedraLayout = new javax.swing.GroupLayout(pedra);
        pedra.setLayout(pedraLayout);
        pedraLayout.setHorizontalGroup(
            pedraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pedraLayout.setVerticalGroup(
            pedraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(pedra);
        pedra.setBounds(390, 30, 100, 100);

        PedraBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pedra.png"))); // NOI18N

        javax.swing.GroupLayout PedraBotLayout = new javax.swing.GroupLayout(PedraBot);
        PedraBot.setLayout(PedraBotLayout);
        PedraBotLayout.setHorizontalGroup(
            PedraBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        PedraBotLayout.setVerticalGroup(
            PedraBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(PedraBot);
        PedraBot.setBounds(390, 230, 100, 100);

        PapelBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/papel.png"))); // NOI18N

        javax.swing.GroupLayout PapelBotLayout = new javax.swing.GroupLayout(PapelBot);
        PapelBot.setLayout(PapelBotLayout);
        PapelBotLayout.setHorizontalGroup(
            PapelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        PapelBotLayout.setVerticalGroup(
            PapelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(PapelBot);
        PapelBot.setBounds(220, 230, 100, 100);

        TesouraBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/tesoura.png"))); // NOI18N

        javax.swing.GroupLayout TesouraBotLayout = new javax.swing.GroupLayout(TesouraBot);
        TesouraBot.setLayout(TesouraBotLayout);
        TesouraBotLayout.setHorizontalGroup(
            TesouraBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        TesouraBotLayout.setVerticalGroup(
            TesouraBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(TesouraBot);
        TesouraBot.setBounds(40, 230, 100, 100);

        TesouraButton.setText("Tesoura");
        TesouraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TesouraButtonActionPerformed(evt);
            }
        });
        jPanel1.add(TesouraButton);
        TesouraButton.setBounds(40, 133, 100, 30);

        PapelButton.setText("Papel");
        PapelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PapelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PapelButton);
        PapelButton.setBounds(220, 133, 100, 30);

        PedraButton.setText("Pedra");
        PedraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedraButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PedraButton);
        PedraButton.setBounds(390, 133, 100, 30);
        jPanel1.add(PontPlayer);
        PontPlayer.setBounds(540, 60, 50, 40);
        jPanel1.add(PontBot);
        PontBot.setBounds(540, 250, 50, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/x.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(570, 0, 30, 30);

        tryagain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/try.png"))); // NOI18N
        tryagain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryagainActionPerformed(evt);
            }
        });
        jPanel1.add(tryagain);
        tryagain.setBounds(540, 180, 40, 40);

        jLabel1.setText("JOGADOR");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(520, 50, 60, 20);

        jLabel2.setText("BOT");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(534, 240, 50, 14);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/dog.jpg"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage1);
        panelImage1.setBounds(0, 0, 500, 400);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(500, 0, 80, 400);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 400);

        setSize(new java.awt.Dimension(600, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TesouraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TesouraButtonActionPerformed
        papel.setVisible(false);
        pedra.setVisible(false);
        PedraButton.setVisible(false);
        PapelButton.setVisible(false);
        TesouraButton.setVisible(false);
        tryagain.setVisible(true);
        Random gera = new Random();
        int machi = 0, jog=3;

    
        machi =  gera.nextInt(3)+1;
        if (machi == 2){
            PapelBot.setVisible(true);
        }else if (machi == 3 ){
            TesouraBot.setVisible(true);
        }else{
            PedraBot.setVisible(true);
        }  
        
         if(machi == 1 && jog == 1 || machi == 2 && jog ==2 || machi == 3 && jog ==3){
         }else if(machi == 1 && jog == 2 || machi == 2 && jog == 3 || machi ==3 && jog ==1){
        contplayer++;
        player = Integer.toString(contplayer); 
    }else{
        contbot++;
        bot = Integer.toString(contbot); 
    }
    PontBot.setText(bot);
        PontPlayer.setText(player);
    }//GEN-LAST:event_TesouraButtonActionPerformed

    private void PapelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PapelButtonActionPerformed
        tesoura.setVisible(false);
        pedra.setVisible(false);
        PedraButton.setVisible(false);
        PapelButton.setVisible(false);
        TesouraButton.setVisible(false);
        tryagain.setVisible(true);
           Random gera = new Random();
        int machi = 0, jog=2;

    
        machi =  gera.nextInt(3)+1;
        if (machi == 2){
            PapelBot.setVisible(true);
        }else if (machi == 3 ){
            TesouraBot.setVisible(true);
        }else{
            PedraBot.setVisible(true);
        }
        if(machi == 1 && jog == 1 || machi == 2 && jog ==2 || machi == 3 && jog ==3){
        }else if(machi == 1 && jog == 2 || machi == 2 && jog == 3 || machi ==3 && jog ==1){
        contplayer++;
        player = Integer.toString(contplayer); 
    }else{
        contbot++;
        bot = Integer.toString(contbot); 
        
    }
        PontBot.setText(bot);
        PontPlayer.setText(player);
    }//GEN-LAST:event_PapelButtonActionPerformed

    private void PedraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedraButtonActionPerformed
        papel.setVisible(false);
        tesoura.setVisible(false);
        PedraButton.setVisible(false);
        PapelButton.setVisible(false);
        TesouraButton.setVisible(false);
        tryagain.setVisible(true);
          Random gera = new Random();
        int machi = 0, jog=1;

    
        machi =  gera.nextInt(3)+1;
        if (machi == 2){
            PapelBot.setVisible(true);
        }else if (machi == 3 ){
            TesouraBot.setVisible(true);
        }else{
            PedraBot.setVisible(true);
        } 
        if(machi == 1 && jog == 1 || machi == 2 && jog ==2 || machi == 3 && jog ==3){
        }else if(machi == 1 && jog == 2 || machi == 2 && jog == 3 || machi ==3 && jog ==1){
        contplayer++;
        player = Integer.toString(contplayer); 
    }else{
        contbot++;
        bot = Integer.toString(contbot); 
    }
      PontBot.setText(bot);
        PontPlayer.setText(player);  
    }//GEN-LAST:event_PedraButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tryagainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryagainActionPerformed
       papel.setVisible(true);
       tesoura.setVisible(true);
       pedra.setVisible(true);
       PedraButton.setVisible(true);
        PapelButton.setVisible(true);
        TesouraButton.setVisible(true);
        PapelBot.setVisible(false);
        PedraBot.setVisible(false);
        TesouraBot.setVisible(false);
        tryagain.setVisible(false);
    }//GEN-LAST:event_tryagainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jokenpo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jokenpo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jokenpo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jokenpo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jokenpo_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.PanelImage PapelBot;
    private javax.swing.JButton PapelButton;
    private org.edisoncor.gui.panel.PanelImage PedraBot;
    private javax.swing.JButton PedraButton;
    private javax.swing.JLabel PontBot;
    private javax.swing.JLabel PontPlayer;
    private org.edisoncor.gui.panel.PanelImage TesouraBot;
    private javax.swing.JButton TesouraButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage papel;
    private org.edisoncor.gui.panel.PanelImage pedra;
    private org.edisoncor.gui.panel.PanelImage tesoura;
    private javax.swing.JButton tryagain;
    // End of variables declaration//GEN-END:variables
}
